# Generated by Django 4.0.3 on 2022-03-13 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stu_id', models.IntegerField(null=True)),
                ('mob_num', models.IntegerField(null=True)),
                ('stu_col', models.TextField(null=True)),
            ],
        ),
    ]
