# Generated by Django 4.0.3 on 2022-03-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stu_col',
            field=models.TextField(choices=[(None, 'Please Select Your College'), ('Veermata Jijabai Technological Institute', 'Veermata Jijabai Technological Institute'), ('Sardar Patel Institute of Technology', 'Sardar Patel Institute of Technology'), ('KJ Somaiya College of Engineering', 'KJ Somaiya College of Engineering'), ('Dwarkadas J Sanghvi College of Engineering', 'Dwarkadas J Sanghvi College of Engineering'), ('Sardar Patel College of Engineering', 'Sardar Patel College of Engineering'), ('Thadomal Shahani Engineering College', 'Thadomal Shahani Engineering College'), ('Vivekanand Education Societys Institute of Technology', 'Vivekanand Education Societys Institute of Technology'), ('KJ Somaiya Institute of Engineering and Information Technology', 'KJ Somaiya Institute of Engineering and Information Technology')], null=True),
        ),
    ]
