# Generated by Django 4.0.3 on 2022-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_course_profile_year_alter_profile_stu_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
