# Generated by Django 4.0.3 on 2022-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='institute',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
