# Generated by Django 4.0.3 on 2022-03-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
