# Generated by Django 4.0.3 on 2022-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[(None, 'Select Category'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Research', 'Research')], max_length=128),
        ),
    ]
