# Generated by Django 4.0.3 on 2022-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plagarised',
            field=models.FloatField(null=True),
        ),
    ]
