# Generated by Django 4.0.3 on 2022-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_plagarised'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plagarised_with',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
