# Generated by Django 4.0.3 on 2022-03-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_plagarised_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='plagarised_with',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
