# Generated by Django 4.0.3 on 2022-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_project_plagarised_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plagarised_with',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
