# Generated by Django 4.0.3 on 2022-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_plagarised_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(default='https://github.com/BasitAnsari/project_manager', max_length=256),
        ),
    ]
